'use client';

import React, { useState } from 'react';
import { Shield, FileText, Scale, Copyright, AlertTriangle, Mail, CheckCircle, ArrowRight } from 'lucide-react';

export default function TermsAndConditions() {
  const [openSections, setOpenSections] = useState({});

  const toggleSection = (section) => {
    setOpenSections(prev => ({
      ...prev,
      [section]: !prev[section]
    }));
  };

  const termsSections = [
    {
      id: 'general',
      icon: <FileText className="w-6 h-6" />,
      title: 'General Terms',
      content: `By accessing and placing an order with Micro Hub Care, you confirm that you are in agreement with and bound by the terms of service contained in the Terms & Conditions outlined below. These terms apply to the entire website and any email or other type of communication between you and Micro Hub Care.`,
      points: [
        'Under no circumstances shall Micro Hub Care team be liable for any direct, indirect, special, incidental or consequential damages',
        'We reserve the rights to change prices and revise the resources usage policy at any moment',
        'Micro Hub Care will not be responsible for any outcome that may occur during the course of usage of our resources'
      ]
    },
    {
      id: 'license',
      icon: <Scale className="w-6 h-6" />,
      title: 'License',
      content: `Micro Hub Care grants you a revocable, non-exclusive, non-transferable, limited license to download, install and use the website strictly in accordance with the terms of this Agreement.`,
      points: [
        'These Terms & Conditions are a contract between you and Micro Hub Care',
        'You are agreeing to be bound by these Terms & Conditions',
        'If you violate any of these Terms & Conditions, we reserve the right to cancel your account'
      ]
    },
    {
      id: 'definitions',
      icon: <FileText className="w-6 h-6" />,
      title: 'Definitions and Key Terms',
      items: [
        {
          term: 'Cookie',
          definition: 'A small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.'
        },
        {
          term: 'Company',
          definition: 'When these terms mention Company, "we," "us," or "our," it refers to Micro Hub Care, that is responsible for your information under these Terms & Conditions.'
        },
        {
          term: 'Country',
          definition: 'Where Micro Hub Care or the owners/founders of Micro Hub Care are based, in this case is the US.'
        },
        {
          term: 'Device',
          definition: 'Any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Micro Hub Care.'
        },
        {
          term: 'Website',
          definition: 'Micro Hub Care site, which can be accessed via this URL: www.microhubcare.com'
        },
        {
          term: 'You',
          definition: 'A person or entity that is registered with Micro Hub Care to use the website.'
        }
      ]
    },
    {
      id: 'restrictions',
      icon: <AlertTriangle className="w-6 h-6" />,
      title: 'Restrictions',
      content: `You agree not to, and you will not permit others to:`,
      points: [
        'License, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose or otherwise commercially exploit the website',
        'Modify, make derivative works of, disassemble, decrypt, reverse compile or reverse engineer any part of the website',
        'Remove, alter or obscure any proprietary notice of Micro Hub Care or its affiliates'
      ]
    },
    {
      id: 'refund',
      icon: <CheckCircle className="w-6 h-6" />,
      title: 'Return and Refund Policy',
      content: `As with any shopping experience, there are terms and conditions that apply to transactions at Micro Hub Care. The main thing to remember is that by placing an order or making a purchase at Micro Hub Care, you agree to the terms along with Micro Hub Care Privacy Policy.`,
      points: [
        'If you are not completely satisfied with any good that we provide, contact us',
        'We will discuss any issues you are going through with our product',
        'All refund requests are subject to our refund policy evaluation'
      ]
    },
    {
      id: 'suggestions',
      icon: <FileText className="w-6 h-6" />,
      title: 'Your Suggestions',
      content: `Any feedback, comments, ideas, improvements or suggestions provided by you to Micro Hub Care with respect to the website shall remain the sole and exclusive property of Micro Hub Care.`,
      points: [
        'Micro Hub Care shall be free to use, copy, modify, publish, or redistribute the Suggestions',
        'No credit or compensation required for suggestions used',
        'Suggestions can be used for any purpose without restriction'
      ]
    },
    {
      id: 'links',
      icon: <ArrowRight className="w-6 h-6" />,
      title: 'Links to Other Websites',
      content: `This website may contain links to other websites not operated or controlled by Micro Hub Care.`,
      points: [
        'We are not responsible for the content, accuracy or opinions expressed in such websites',
        'Your browsing on other websites is subject to that website\'s own rules and policies',
        'Our Terms & Conditions are no longer in effect when you leave our website'
      ]
    },
    {
      id: 'cookies',
      icon: <Shield className="w-6 h-6" />,
      title: 'Cookies',
      content: `Micro Hub Care uses "Cookies" to identify the areas of our website that you have visited.`,
      points: [
        'Cookies enhance the performance and functionality of our website',
        'We never place Personally Identifiable Information in Cookies',
        'Disabling Cookies may limit website functionality'
      ]
    },
    {
      id: 'changes',
      icon: <FileText className="w-6 h-6" />,
      title: 'Changes To Our Terms & Conditions',
      content: `You acknowledge and agree that Micro Hub Care reserves the right to cease providing the website to you or to users, either permanently or temporarily, at our sole discretion, without prior notice.`,
      points: [
        'We may disable access to your account for violations',
        'Changes will be posted on this page with updated dates',
        'Continued use constitutes acceptance of changes'
      ]
    },
    {
      id: 'warranties',
      icon: <AlertTriangle className="w-6 h-6" />,
      title: 'No Warranties',
      content: `Without limiting the foregoing, neither Micro Hub Care nor any provider makes any representation or warranty of any kind, express or implied.`,
      points: [
        'No guarantee of uninterrupted or error-free service',
        'No warranty for accuracy, reliability, or currency of information',
        'Website provided "as is" without any warranties'
      ]
    },
    {
      id: 'liability',
      icon: <Scale className="w-6 h-6" />,
      title: 'Limitation of Liability',
      content: `Notwithstanding any damages that you might incur, the entire liability of Micro Hub Care and any of its suppliers shall be limited to the amount actually paid by you for the website.`,
      points: [
        'Liability limited to purchase amount',
        'No liability for indirect or consequential damages',
        'Specific disclaimers apply as outlined in full terms'
      ]
    },
    {
      id: 'intellectual',
      icon: <Copyright className="w-6 h-6" />,
      title: 'Intellectual Property',
      content: `The website and its entire contents, features and functionality are owned by Micro Hub Care and are protected by US and international copyright, trademark, patent, trade secret and other intellectual property laws.`,
      points: [
        'Material may not be copied, modified, reproduced without permission',
        'Protected by international intellectual property laws',
        'Unauthorized use of material is prohibited'
      ]
    }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-blue-50 py-12">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="text-center mb-12">
          <div className="flex justify-center mb-6">
            <div className="w-20 h-20 bg-gradient-to-br from-[#59c7b5] to-[#0095d4] rounded-2xl flex items-center justify-center shadow-2xl">
              <Shield className="w-10 h-10 text-white" />
            </div>
          </div>
          <h1 className="text-4xl lg:text-5xl font-bold text-gray-800 mb-4">
            Terms & <span className="text-[#0095d4]">Conditions</span>
          </h1>
          <p className="text-xl text-gray-600 max-w-2xl mx-auto">
            Last updated {new Date().toLocaleDateString('en-US', { 
              year: 'numeric', 
              month: 'long', 
              day: 'numeric' 
            })}
          </p>
        </div>

        {/* Quick Summary */}
        <div className="bg-white/80 backdrop-blur-sm rounded-3xl p-8 border border-white/20 shadow-2xl mb-8">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 text-center">
            <div className="p-4">
              <div className="w-12 h-12 bg-blue-100 rounded-2xl flex items-center justify-center mx-auto mb-3">
                <FileText className="w-6 h-6 text-blue-600" />
              </div>
              <h3 className="font-semibold text-gray-800 mb-1">Legal Agreement</h3>
              <p className="text-gray-600 text-sm">Binding contract between you and Micro Hub Care</p>
            </div>
            <div className="p-4">
              <div className="w-12 h-12 bg-green-100 rounded-2xl flex items-center justify-center mx-auto mb-3">
                <CheckCircle className="w-6 h-6 text-green-600" />
              </div>
              <h3 className="font-semibold text-gray-800 mb-1">Your Consent</h3>
              <p className="text-gray-600 text-sm">By using our website, you agree to these terms</p>
            </div>
            <div className="p-4">
              <div className="w-12 h-12 bg-amber-100 rounded-2xl flex items-center justify-center mx-auto mb-3">
                <AlertTriangle className="w-6 h-6 text-amber-600" />
              </div>
              <h3 className="font-semibold text-gray-800 mb-1">Important</h3>
              <p className="text-gray-600 text-sm">Please read these terms carefully</p>
            </div>
          </div>
        </div>

        {/* Terms Sections */}
        <div className="space-y-6">
          {termsSections.map((section) => (
            <div 
              key={section.id}
              className="bg-white/80 backdrop-blur-sm rounded-3xl border border-white/20 shadow-2xl overflow-hidden transition-all duration-300 hover:shadow-xl"
            >
              <button
                onClick={() => toggleSection(section.id)}
                className="w-full p-8 text-left flex items-center justify-between hover:bg-gray-50/50 transition-colors duration-200"
              >
                <div className="flex items-center gap-4">
                  <div className="flex-shrink-0 w-12 h-12 bg-gradient-to-br from-[#59c7b5] to-[#0095d4] rounded-xl flex items-center justify-center">
                    {section.icon}
                  </div>
                  <div>
                    <h3 className="text-xl font-bold text-gray-800">
                      {section.title}
                    </h3>
                    <p className="text-gray-600 mt-1 text-sm">
                      Click to {openSections[section.id] ? 'collapse' : 'expand'} details
                    </p>
                  </div>
                </div>
                <div className={`transform transition-transform duration-300 ${openSections[section.id] ? 'rotate-180' : ''}`}>
                  <svg className="w-6 h-6 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                  </svg>
                </div>
              </button>

              {openSections[section.id] && (
                <div className="px-8 pb-8">
                  <div className="border-t border-gray-200 pt-6">
                    {/* Content */}
                    {section.content && (
                      <p className="text-gray-600 mb-6 leading-relaxed">
                        {section.content}
                      </p>
                    )}

                    {/* Definitions List */}
                    {section.items && (
                      <div className="space-y-4">
                        {section.items.map((item, index) => (
                          <div key={index} className="bg-gray-50 rounded-xl p-4 border border-gray-200">
                            <div className="flex items-start gap-3">
                              <div className="flex-shrink-0 w-2 h-2 bg-[#0095d4] rounded-full mt-2"></div>
                              <div>
                                <h4 className="font-semibold text-gray-800 mb-1">
                                  {item.term}
                                </h4>
                                <p className="text-gray-600 text-sm">
                                  {item.definition}
                                </p>
                              </div>
                            </div>
                          </div>
                        ))}
                      </div>
                    )}

                    {/* Points List */}
                    {section.points && (
                      <div className="space-y-3">
                        {section.points.map((point, index) => (
                          <div key={index} className="flex items-start gap-3">
                            <div className="flex-shrink-0 w-5 h-5 bg-blue-100 rounded-full flex items-center justify-center mt-0.5">
                              <div className="w-2 h-2 bg-[#0095d4] rounded-full"></div>
                            </div>
                            <p className="text-gray-600 flex-1">
                              {point}
                            </p>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>
                </div>
              )}
            </div>
          ))}
        </div>

        {/* Consent Section */}
        <div className="bg-gradient-to-r from-[#59c7b5] to-[#0095d4] rounded-3xl p-8 text-white shadow-2xl mt-8">
          <div className="flex items-center gap-4 mb-4">
            <CheckCircle className="w-8 h-8" />
            <h3 className="text-2xl font-bold">Your Consent</h3>
          </div>
          <p className="text-white/90 mb-4 leading-relaxed">
            We've updated our Terms & Conditions to provide you with complete transparency into what is being set 
            when you visit our site and how it's being used. By using our website, registering an account, or 
            making a purchase, you hereby consent to our Terms & Conditions.
          </p>
        </div>

        {/* Contact Section */}
        <div className="bg-white/80 backdrop-blur-sm rounded-3xl p-8 border border-white/20 shadow-2xl mt-8">
          <div className="flex items-center gap-4 mb-4">
            <Mail className="w-8 h-8 text-[#0095d4]" />
            <h3 className="text-2xl font-bold text-gray-800">Contact Us</h3>
          </div>
          <p className="text-gray-600 mb-4">
            Don't hesitate to contact us if you have any questions regarding these Terms & Conditions.
          </p>
          <div className="flex items-center gap-2">
            <span className="font-semibold text-gray-800">Via Email:</span>
            <a 
              href="mailto:sales@microhubcare.com" 
              className="text-[#0095d4] hover:text-[#0077b6] transition-colors duration-200 underline"
            >
              sales@microhubcare.com
            </a>
          </div>
        </div>

        {/* Legal Notice */}
        <div className="text-center mt-8">
          <p className="text-gray-500 text-sm">
            © {new Date().getFullYear()} Micro Hub Care. All rights reserved.
          </p>
        </div>
      </div>
    </div>
  );
}